### ISSUE TITLE
Agent numbering reuse causes confusing build history

### ISSUE THREAD

**Issue by benesch** [JetBrains/teamcity-google-agent#11]
Unlike the Azure plugin, where agent names are never reused, the GCE plugin seems to reuse names when possible. For example, if an idle agent, say "gce-agent-7", is terminated, that name becomes available for reuse when new agents are started.

Because TeamCity seems to use the agent name as its identity, the "Build History" tab will show builds from every "gce-agent-7" ever created. This is quite confusing.

Is this behavior intentional or is it a bug?

**Comment by dtretyakov** [comment]
@benesch, it's an intentional behavior, the same agents numbering is used in Azure ARM plugin.

We could introduce toggle between current numbering scheme and growing ids as in old Azure plugin versions.

**Comment by dtretyakov** [comment]
@benesch, plugin with this feature is available in the plugins repository: https://plugins.jetbrains.com/plugin/9704-google-cloud-agents
