### ISSUE TITLE
preemptible instances are leaked when preempted

### ISSUE THREAD

**Issue by benesch** [JetBrains/teamcity-google-agent#14]
Preemptible instances that are preempted by GCE are "leaked" in that they are stuck forever in the "Stopped" state as show below:

<img width="1132" alt="screenshot 2017-12-13 00 00 24" src="https://user-images.githubusercontent.com/882976/33924219-099de732-dfa3-11e7-8186-a447f76b5aab.png">

Preemption happens pretty frequently with some of the larger instance types, so would be great to have them automatically cleaned up. Even though the instance isn't billed when in the "Stopped" state, the persistent disk is.

In case someone else has the same issue, as a workaround for now, we're running the following script every hour:

```
gcloud compute instances list --format json \
  | ./jq -r '.[] | select (.scheduling.preemptible == true and .status == "TERMINATED") | .name  + " --zone " + .zone' \
  | xargs -tL1 gcloud compute instances delete --delete-disks all
```

**Comment by dtretyakov** [comment]
@benesch, thanks for reporting it, will implement this improvement.

**Comment by dtretyakov** [comment]
@benesch, plugin also available in the plugins repository: https://plugins.jetbrains.com/plugin/9704-google-cloud-agents
