### ISSUE TITLE
Unable to edit/delete agent images after deleting the associated cloud image 

### ISSUE THREAD

**Issue by steazzalini** [JetBrains/teamcity-google-agent#15]
To reproduce:
 - Add an agent image associated with an existing Cloud Image
 - From Google Console, delete the Cloud Image used in the step before
 - Try to edit the agent

Seems like this scenario is not taken into account in some js logic:
 `Uncaught TypeError: self.sourceImages(...).every is not a function`

**Comment by dtretyakov** [comment]
@steazzalini, could you please also specify the version of plugin?

**Comment by dtretyakov** [comment]
@steazzalini, it should be fixed in the [latest snapshot plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityGoogleCloudAgent_Build&guest=1).

**Comment by steazzalini** [comment]
@dtretyakov Thanks!
