### ISSUE TITLE
Better explanation for scopes

### ISSUE THREAD

**Issue by supersteves** [JetBrains/teamcity-google-agent#20]
It took a lot of head-scratching to realise why the scope "cloud-platform" didn't work. which works when using gcloud command. 

Instead here you need to use the URL: "https://www.googleapis.com/auth/cloud-platform" for example. Some popup help would be useful here.

**Comment by dtretyakov** [comment]
@supersteves, thanks for letting me know about it. In the next version it will provide a help popup.
