### ISSUE TITLE
Not possible to create profile because "No networks found in the project"

### ISSUE THREAD

**Issue by petemounce** [JetBrains/teamcity-google-agent#5]
## What were you trying to do?
Set up a Google Cloud Engine Windows agent 

## What happened? How can we reproduce?

0. Install TeamCity (running via docker) `2017.1.3`
0. Install cloud-google `0.5.0`
0. Create a cloud profile - give it a name, pick GCE
0. Give it a service account key (where that service account has `Compute Instance Admin v1` role, only.
  * (I also tried with `Compute Instance Admin v1` _and_ `Compute Network Viewer` (in that order), and in that case, the plugin tells me that it cannot list zones or images or one other operation)
0. Result:
<img width="305" alt="teamcity-gce-no-networks-found" src="https://user-images.githubusercontent.com/69720/29662110-0c967e68-88be-11e7-9d0d-c7feeee394f9.PNG">

But I have these networks defined: <img width="492" alt="gc-networks-minus-details" src="https://user-images.githubusercontent.com/69720/29662111-0c964c54-88be-11e7-889d-4521b2fcd87d.png">

## What did you expect to have happen?

Either of:
* I would be allowed to choose one of the networks within my project
* I am told _why_ the plugin could not find any networks

**Comment by petemounce** [comment]
I have found and read https://github.com/JetBrains/teamcity-google-agent/issues/4#issuecomment-314036304, tried out modifying my service account to add `Compute Network Viewer`, and after recreating the Cloud Profile (since apparently, it caches what it gets and doesn't revoke it when the key is re-added or the dialog cancelled), same error.

`Compute Instance Admin v1` permissions:
```
compute.acceleratorTypes.get
compute.acceleratorTypes.list
compute.addresses.get
compute.addresses.list
compute.addresses.use
compute.autoscalers.create
compute.autoscalers.delete
compute.autoscalers.get
compute.autoscalers.list
compute.autoscalers.update
compute.backendBuckets.get
compute.backendBuckets.list
compute.backendServices.get
compute.backendServices.list
compute.diskTypes.get
compute.diskTypes.list
compute.disks.create
compute.disks.createSnapshot
compute.disks.delete
compute.disks.get
compute.disks.list
compute.disks.resize
compute.disks.setLabels
compute.disks.update
compute.disks.use
compute.disks.useReadOnly
compute.firewalls.get
compute.firewalls.list
compute.forwardingRules.externalGet
compute.forwardingRules.get
compute.forwardingRules.list
compute.globalAddresses.get
compute.globalAddresses.list
compute.globalAddresses.use
compute.globalForwardingRules.get
compute.globalForwardingRules.list
compute.globalOperations.get
compute.globalOperations.list
compute.healthChecks.get
compute.healthChecks.list
compute.httpHealthChecks.get
compute.httpHealthChecks.list
compute.httpsHealthChecks.get
compute.httpsHealthChecks.list
compute.images.create
compute.images.delete
compute.images.deprecate
compute.images.get
compute.images.getFromFamily
compute.images.list
compute.images.setLabels
compute.images.update
compute.images.useReadOnly
compute.instanceGroupManagers.create
compute.instanceGroupManagers.delete
compute.instanceGroupManagers.get
compute.instanceGroupManagers.list
compute.instanceGroupManagers.update
compute.instanceGroupManagers.use
compute.instanceGroups.create
compute.instanceGroups.delete
compute.instanceGroups.get
compute.instanceGroups.list
compute.instanceGroups.update
compute.instanceGroups.use
compute.instanceTemplates.create
compute.instanceTemplates.delete
compute.instanceTemplates.get
compute.instanceTemplates.list
compute.instanceTemplates.useReadOnly
compute.instances.addAccessConfig
compute.instances.attachDisk
compute.instances.create
compute.instances.delete
compute.instances.deleteAccessConfig
compute.instances.detachDisk
compute.instances.get
compute.instances.getGuestAttributes
compute.instances.getSerialPortOutput
compute.instances.list
compute.instances.listReferrers
compute.instances.osAdminLogin
compute.instances.osLogin
compute.instances.reset
compute.instances.setDiskAutoDelete
compute.instances.setLabels
compute.instances.setMachineType
compute.instances.setMetadata
compute.instances.setScheduling
compute.instances.setTags
compute.instances.start
compute.instances.startWithEncryptionKey
compute.instances.stop
compute.instances.update
compute.instances.use
compute.interconnectAttachments.get
compute.interconnectAttachments.list
compute.interconnectLocations.get
compute.interconnectLocations.list
compute.interconnects.get
compute.interconnects.list
compute.licenses.create
compute.licenses.get
compute.licenses.list
compute.machineTypes.get
compute.machineTypes.list
compute.networks.get
compute.networks.list
compute.networks.use
compute.networks.useExternalIp
compute.operations.get
compute.operations.list
compute.projects.get
compute.projects.setCommonInstanceMetadata
compute.regionOperations.get
compute.regionOperations.list
compute.regions.get
compute.regions.list
compute.routers.get
compute.routers.list
compute.routes.get
compute.routes.list
compute.snapshots.create
compute.snapshots.delete
compute.snapshots.get
compute.snapshots.list
compute.snapshots.setLabels
compute.snapshots.update
compute.snapshots.useReadOnly
compute.sslCertificates.get
compute.sslCertificates.list
compute.sslPolicies.get
compute.sslPolicies.list
compute.sslPolicies.listAvailableFeatures
compute.subnetworks.get
compute.subnetworks.list
compute.subnetworks.use
compute.subnetworks.useExternalIp
compute.targetHttpProxies.get
compute.targetHttpProxies.list
compute.targetHttpsProxies.get
compute.targetHttpsProxies.list
compute.targetInstances.get
compute.targetInstances.list
compute.targetPools.get
compute.targetPools.list
compute.targetSslProxies.get
compute.targetSslProxies.list
compute.targetVpnGateways.get
compute.targetVpnGateways.list
compute.urlMaps.get
compute.urlMaps.list
compute.vpnTunnels.get
compute.vpnTunnels.list
compute.zoneOperations.get
compute.zoneOperations.list
compute.zones.get
compute.zones.list
resourcemanager.projects.get
resourcemanager.projects.list
serviceusage.quotas.get
serviceusage.services.get
```

`Compute Network Viewer` permissions:
```
compute.addresses.get
compute.addresses.list
compute.backendBuckets.get
compute.backendBuckets.list
compute.backendServices.get
compute.backendServices.list
compute.firewalls.get
compute.firewalls.list
compute.forwardingRules.externalGet
compute.forwardingRules.get
compute.forwardingRules.list
compute.globalAddresses.get
compute.globalAddresses.list
compute.globalForwardingRules.get
compute.globalForwardingRules.list
compute.healthChecks.get
compute.healthChecks.list
compute.httpHealthChecks.get
compute.httpHealthChecks.list
compute.httpsHealthChecks.get
compute.httpsHealthChecks.list
compute.instanceGroups.get
compute.instanceGroups.list
compute.instances.get
compute.instances.getGuestAttributes
compute.instances.getSerialPortOutput
compute.instances.list
compute.instances.listReferrers
compute.interconnectAttachments.get
compute.interconnectAttachments.list
compute.interconnectLocations.get
compute.interconnectLocations.list
compute.interconnects.get
compute.interconnects.list
compute.networks.get
compute.networks.list
compute.networks.listIpOwners
compute.networks.listUsableSubnets
compute.projects.get
compute.regions.get
compute.regions.list
compute.routers.get
compute.routers.list
compute.routes.get
compute.routes.list
compute.scopes.get
compute.scopes.list
compute.sslCertificates.get
compute.sslCertificates.list
compute.sslPolicies.get
compute.sslPolicies.list
compute.sslPolicies.listAvailableFeatures
compute.subnetworks.get
compute.subnetworks.list
compute.subnetworks.listIpOwners
compute.targetHttpProxies.get
compute.targetHttpProxies.list
compute.targetHttpsProxies.get
compute.targetHttpsProxies.list
compute.targetInstances.get
compute.targetInstances.list
compute.targetPools.get
compute.targetPools.list
compute.targetSslProxies.get
compute.targetSslProxies.list
compute.targetVpnGateways.get
compute.targetVpnGateways.list
compute.urlMaps.get
compute.urlMaps.list
compute.vpnTunnels.get
compute.vpnTunnels.list
compute.zones.get
compute.zones.list
resourcemanager.projects.get
resourcemanager.projects.list
serviceusage.quotas.get
serviceusage.services.get
```

It would be great if the readme listed the specific permissions that are required, too, so one could create a least-privilege role specifically for this rather than give blanket permissions.

**Comment by dtretyakov** [comment]
@petemounce, thanks for reporting. We'll try to improve error reporting and share the complete list of required permissions.

**Comment by petemounce** [comment]
@dtretyakov Thanks. Please let me know if you need any other information from me.

**Comment by kszarek** [comment]
It does not work for us as well. @dtretyakov do you know when it it going to be fixed? Plugin does not work for 2017.1.3/4 version.

**Comment by dtretyakov** [comment]
@petemounce, @kszarek, what roles did you granted to the TeamCity service account in the Google Cloud IAM?

**Comment by petemounce** [comment]
From the original report:
> Give it a service account key (where that service account has `Compute Instance Admin v1` role, only.
> (I also tried with `Compute Instance Admin v1` and `Compute Network Viewer` (in that order), and in that case, the plugin tells me that it cannot list zones or images or one other operation)

**Comment by dtretyakov** [comment]
@petemounce, could you try completely delete teamcity service account entry on the IAM page and then add them again by clicking `ADD` button, typing service account name and granting roles?

If it also does not help, please enable Resource manager API, navigate to the cloud profile to look at the "No networks found in the project" message and then provide `teamcity-clouds.log` [server log file](https://confluence.jetbrains.com/display/TCDL/TeamCity+Server+Logs).

**Comment by petemounce** [comment]
I attempted to create the cloud profile again, and I can see `[2017-09-12 12:47:35,433]   WARN [o-8111-exec-146] - .beans.CloudTabFormFactoryImpl - Can't find projectId by projectExtId '' ` as the most recent message. Sounds like it might be an error rather than a warning.

Can I turn up the verbosity of this logging? If so, how, please?

**Comment by dtretyakov** [comment]
@petemounce, "Can't find projectId by projectExtId" is a side issue. Could you please check what result returns the [compute.networks.list](https://developers.google.com/apis-explorer/#p/compute/v1/compute.networks.list) method for this project id?

**Comment by petemounce** [comment]
Sure - how do I configure the teamcity logs to that level of detail?

Or, do you mean I should look in the google cloud resource manager API? If the latter - there's no request there other than a 200 OK, and I assume that's the one that fetches the list of images. It doesn't look like I can see response bodies via that (?).

**Comment by dtretyakov** [comment]
@petemounce, the last response is from the [compute.networks.list](https://developers.google.com/apis-explorer/#p/compute/v1/compute.networks.list) method. If you don't see any networks please navigate to the [VPC networks](https://console.cloud.google.com/networking/networks/list) and create a new one if you don't see any.
It should look like that:
![image](https://user-images.githubusercontent.com/1025927/30391608-b5c744a4-98c2-11e7-8c89-0a81f3e586b5.png)

**Comment by petemounce** [comment]
I have VPCs already; here's a slightly obfuscated shot:
<img width="452" alt="vpcs" src="https://user-images.githubusercontent.com/69720/30489278-c06d9b20-9a2e-11e7-91f6-40de6c947bbd.PNG">

**Comment by kszarek** [comment]
Maybe, that's the case. I also don't use the default network.

**Comment by petemounce** [comment]
In using the top one.

**Comment by dtretyakov** [comment]
@petemounce, thanks for details, we'll check this problem with networks in Custom and Legacy modes.

**Comment by petemounce** [comment]
Hi - any update?

**Comment by dtretyakov** [comment]
@petemounce, @kszarek, @mxpv this problem was fixed, please update the plugin: https://plugins.jetbrains.com/plugin/9704-google-cloud-agents
