### ISSUE TITLE
Possible to define instance metadata for startup scripts?

### ISSUE THREAD

**Issue by petemounce** [JetBrains/teamcity-google-agent#6]
I have a requirement to apply licenses to software within an instance before that can be used. I cannot bake that into the image; it must happen at instance-run-time, not image-build-time.

A really convenient way to do this would be via [a google startup script](https://cloud.google.com/compute/docs/startupscript). I need to use both Linux and Windows machines, here.

Is this functionality planned?

**Comment by dtretyakov** [comment]
@petemounce, thanks for reporting. We'll consider implementing it.

**Comment by benesch** [comment]
Shutdown scripts would be quite helpful too, especially when using preemptible instances!

**Comment by dtretyakov** [comment]
@petemounce, @benesch in [the latest snapshot build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityGoogleCloudAgent_Build&guest=1) it's possible to specify custom metadata for instance:
![image](https://user-images.githubusercontent.com/1025927/33841304-a91a30fc-de97-11e7-95a4-4d25cfe0ff71.png)

So you could specify [startup](https://cloud.google.com/compute/docs/startupscript) and [shutdown](https://cloud.google.com/compute/docs/shutdownscript) scripts like that:
```json
{
  "startup-script": "#! /bin/bash\n\n# Installs apache and a custom homepage\napt-get update\napt-get install -y apache2\ncat <<EOF > /var/www/html/index.html\n<html><body><h1>Hello World</h1>\n<p>This page was created from a simple start up script!</p>\n</body></html>",
  "shutdown-script": "#! /bin/bash\n\n# Shuts down Apache server\n/etc/init.d/apache2 stop"
}
```

**Comment by benesch** [comment]
Works great! Thanks!

FYI we've found specifying the following shutdown script for preemptible agents to be helpful:

```
{
  "shutdown-script": "sudo -u agent /home/agent/bin/agent.sh stop force"
}
```

With this in place, TeamCity will auto-requeue the build for retry on another agent. (Otherwise, TeamCity marks the build as canceled but does not requeue it.) Would be nice if TeamCity handled this out-of-the-box somehow, but this does the trick nicely for now!
