### ISSUE TITLE
Support the disk type configurable

### ISSUE THREAD

**Issue by nikita-shvinagir** [JetBrains/teamcity-google-agent#7]
Looks like at the moment all VM instances, that are created from custom images, are created with the standard persistent disk as a boot disk by default.

Is it possible to implement possibility of configuring the disk type [pd-ssd/pd-standard]?

Our application is very demanding for build performance and using SSD disks for VM instances will definitely increase the performance.

**Comment by dtretyakov** [comment]
@nikita-shvinagir, you could [update your plugin](https://plugins.jetbrains.com/plugin/9704-google-cloud-agents).

**Comment by nikita-shvinagir** [comment]
Thank you!

**Comment by dhatawesomedude** [comment]
@nikita-shvinagir How did you go about updating the plugin? I can't find any resource on how to update 3rd party plugins on Teamcity.

**Comment by nikita-shvinagir** [comment]
@dhatawesomedude you just remove the old version from the <TeamCity Data Directory>/plugins folder and copy\unzip the new one into it.

**Comment by dhatawesomedude** [comment]
thanks @nikita-shvinagir  that did the trick. Although, in my case, I used the UI - Deleted the old version, and added the new one.

**Comment by matti-cujo** [comment]
This does not actually seem to be working. Whether "Standard Persistent Disk" or "SSD Persistent Disk" is selected, GCP shows that the created instances have Standard persistent disks.

**Comment by dtretyakov** [comment]
@matti-cujo, thanks for reporting will check it. It may be caused by recent update of Google Cloud SDK in the plugin.

**Comment by dtretyakov** [comment]
@matti-cujo, it should be fixed in the [latest bug fix update 0.7.2](https://plugins.jetbrains.com/plugin/9704-google-cloud-agents).
