### ISSUE TITLE
Custom CPU and memory instances

### ISSUE THREAD

**Issue by benesch** [JetBrains/teamcity-google-agent#9]
Any chance you could add support for [custom machine types](https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type)? None of the stock machine sizes are quite right for our workload, so it would be great to be able to specify a custom number of CPUs/amount of memory for the created agents.

Thanks for an awesome plugin!

**Comment by dtretyakov** [comment]
@benesch, thanks for this request, we'll support custom machine types in the next version.

**Comment by dtretyakov** [comment]
@benesch, you could try to download [the latest snapshot build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityGoogleCloudAgent_Build&guest=1) of this plugin and let me know if it resolves your use case.

**Comment by benesch** [comment]
It worked perfectly! Thank you so much!
